### ISSUE TITLE
Unable to install fastpca through conda

### ISSUE THREAD

**Issue by ashrayar** [moldyn/FastPCA#2]
Hi, I am trying to install fastpca using conda with the command given in README (`conda install -c conda-forge fastpca`) but keep getting the PackagesNotFoundError.

**Comment by simonbray** [comment]
Can you provide the full command and error please?

Are you installing into the base environment? If so can you try creating a new environment, that is highly recommended. Have you tried appending `--override-channels` to the command?

Best wishes,

Simon

**Comment by simonbray** [comment]
Oh, another thought: what OS are you on? The conda package is only available for Linux.

**Comment by ashrayar** [comment]
Hi Simon,

I tried this on macOS. But let me give it a try now on linux. Thanks for
getting back!


Regards,
Ashraya

**Comment by ashrayar** [comment]
The conda installation worked on a linux environment. Thanks again!
 I have a PDB file with multiple models and I want to perform dPCA+ on all dihedral angles. How should I format the input? Should it be a text file with the just the dihedral angles or should it be the sin/cos values of the angles?

**Comment by braniii** [comment]
@simonbray thx for helping out

If you want to perform dPCA+ you need to provide a text file where each column corresponds to a dihedral angle together with the flag `--periodic`. It should be noted that the angle should be given in degrees! Here you can find an [example input file for HP35](https://github.com/moldyn/HP35-DESRES). And maybe one further note: performing PCA on sin/cos values is known as dPCA (no plus in this case).
